version: 0.2

phases:
build:
commands:
- echo "Deploying to EC2"

```
  - aws ssm send-command \
    --instance-ids i-043a237a6648bcbaf \
    --document-name "AWS-RunShellScript" \
    --parameters commands="/home/ubuntu/deploy/deploy.sh" \
    --region ap-south-1
```

